markdown: kramdown
permalink: /blog/:categories/:title
title: Stefan Moraru
email: stefan@stefanmoraru.ro
description: Full stack developer with a snappy mind
baseurl: ""
url: "http://stefanmoraru.ro"
